#!/usr/bin/env bash

set -e

if [[ -f ".git/hooks/.changed" ]]; then
    git_rev=$(git rev-parse HEAD)
    rm .git/hooks/.changed
    echo "${git_rev}" > .git/hooks/hooks-revision
    echo "${git_rev}" > tools/git-hooks/hooks-revision
    git add tools/git-hooks/hooks-revision > /dev/null
    git commit --amend --no-edit --no-verify > /dev/null
    echo -e "\e[32;1mUpdated git hooks revision to \e[33;1m${git_rev}\e[0m"
fi

if ! command -v git-lfs > /dev/null; then
  echo -e "\e[31;1mGit LFS is not installed!:\e[0m"
  echo -e "\e[31;1mSee \e[33;1mhttps://git-lfs.github.com/\e[0m\e[31;1m for more info \e[0m"
  exit 1
fi

git lfs post-commit "$@"

