// FILE: C:/Users/David/Documents/MC/force-src/src/main/native/vulkan_mod/itexture.cpp

#include "itexture.h"

namespace vulkan_mod {



    // Operations

void itexture::set_data(std::vector<float> data, int height, int width, int channels)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B53 begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B53 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace vulkan_mod */
