// FILE: C:/Users/David/Documents/MC/force-src/src/main/native/vulkan_mod/mc_chunk.cpp

#include "mc_chunk.h"

namespace vulkan_mod {


    /** 
     *  Represents a chunk from Minecraft.
     *  
     *  Chunks should be updated from Minecraft every render loop. I can make this pull data from Minecraft's RenderChunk maybe?
     */


    // Operations


/** 
     *  Returns this chunk's vertex buffer
     */
ivertex_buffer mc_chunk::get_vertex_buffer()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B98 begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B98 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace vulkan_mod */
