// FILE: C:/Users/David/Documents/MC/force-src/src/main/native/vulkan_mod/time.cpp

#include "time.h"

namespace vulkan_mod {


    /** 
     *  Represents time
     */


    // Operations


/** 
     *  Returns the time in seconds since Minecraft was started
     */
double time::get_cur_time()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000BBC begin
{
    return 0.0;
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000BBC end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Returns the time in seconds that the last frame took to render
     */
double time::get_delta_time()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000BC0 begin
{
    return 0.0;
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000BC0 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Reads the CPU clock to know when the frame started rendering.
     *  
     *  Also updates delta time and current time
     */
void time::start_frame()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000BC7 begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000BC7 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace vulkan_mod */
