package com.continuum.nova.transformers.Minecraft;

import com.continuum.nova.transformers.BetterMethodVisitor;
import org.objectweb.asm.Label;
import org.objectweb.asm.Opcodes;

import static org.objectweb.asm.Opcodes.*;

/**
 * @author David
 */
public class StartGameReplacer extends BetterMethodVisitor {
    public StartGameReplacer() {
        super();
    }

    @Override
    public void visitCode() {
        Label l0 = new Label();
        Label l1 = new Label();
        Label l2 = new Label();
        mv.visitTryCatchBlock(l0, l1, l2, "org/lwjgl/opengl/OpenGLException");
        Label l3 = new Label();
        mv.visitLabel(l3);
        mv.visitLineNumber(429, l3);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/settings/GameSettings");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcDataDir", "Ljava/io/File;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/settings/GameSettings", "<init>", "(Lnet/minecraft/client/Minecraft;Ljava/io/File;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        Label l4 = new Label();
        mv.visitLabel(l4);
        mv.visitLineNumber(430, l4);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "defaultResourcePacks", "Ljava/util/List;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcDefaultResourcePack", "Lnet/minecraft/client/resources/DefaultResourcePack;");
        mv.visitMethodInsn(INVOKEINTERFACE, "java/util/List", "add", "(Ljava/lang/Object;)Z", true);
        mv.visitInsn(POP);
        Label l5 = new Label();
        mv.visitLabel(l5);
        mv.visitLineNumber(431, l5);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "startTimerHackThread", "()V", false);
        Label l6 = new Label();
        mv.visitLabel(l6);
        mv.visitLineNumber(433, l6);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "overrideHeight", "I");
        Label l7 = new Label();
        mv.visitJumpInsn(IFLE, l7);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "overrideWidth", "I");
        mv.visitJumpInsn(IFLE, l7);
        Label l8 = new Label();
        mv.visitLabel(l8);
        mv.visitLineNumber(435, l8);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "overrideWidth", "I");
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "displayWidth", "I");
        Label l9 = new Label();
        mv.visitLabel(l9);
        mv.visitLineNumber(436, l9);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "overrideHeight", "I");
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "displayHeight", "I");
        mv.visitLabel(l7);
        mv.visitLineNumber(439, l7);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitFieldInsn(GETSTATIC, "net/minecraft/client/Minecraft", "logger", "Lorg/apache/logging/log4j/Logger;");
        mv.visitTypeInsn(NEW, "java/lang/StringBuilder");
        mv.visitInsn(DUP);
        mv.visitMethodInsn(INVOKESPECIAL, "java/lang/StringBuilder", "<init>", "()V", false);
        mv.visitLdcInsn("LWJGL Version: ");
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/Sys", "getVersion", "()Ljava/lang/String;", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "append", "(Ljava/lang/String;)Ljava/lang/StringBuilder;", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "java/lang/StringBuilder", "toString", "()Ljava/lang/String;", false);
        mv.visitMethodInsn(INVOKEINTERFACE, "org/apache/logging/log4j/Logger", "info", "(Ljava/lang/String;)V", true);
        Label l10 = new Label();
        mv.visitLabel(l10);
        mv.visitLineNumber(440, l10);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "setWindowIcon", "()V", false);
        Label l11 = new Label();
        mv.visitLabel(l11);
        mv.visitLineNumber(441, l11);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "setInitialDisplayMode", "()V", false);
        Label l12 = new Label();
        mv.visitLabel(l12);
        mv.visitLineNumber(442, l12);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "createDisplay", "()V", false);
        Label l13 = new Label();
        mv.visitLabel(l13);
        mv.visitLineNumber(443, l13);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/OpenGlHelper", "initializeTextures", "()V", false);
        Label l14 = new Label();
        mv.visitLabel(l14);
        mv.visitLineNumber(444, l14);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/shader/Framebuffer");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "displayWidth", "I");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "displayHeight", "I");
        mv.visitInsn(ICONST_1);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/shader/Framebuffer", "<init>", "(IIZ)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "framebufferMc", "Lnet/minecraft/client/shader/Framebuffer;");
        Label l15 = new Label();
        mv.visitLabel(l15);
        mv.visitLineNumber(445, l15);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "framebufferMc", "Lnet/minecraft/client/shader/Framebuffer;");
        mv.visitInsn(FCONST_0);
        mv.visitInsn(FCONST_0);
        mv.visitInsn(FCONST_0);
        mv.visitInsn(FCONST_0);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/shader/Framebuffer", "setFramebufferColor", "(FFFF)V", false);
        Label l16 = new Label();
        mv.visitLabel(l16);
        mv.visitLineNumber(446, l16);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "registerMetadataSerializers", "()V", false);
        Label l17 = new Label();
        mv.visitLabel(l17);
        mv.visitLineNumber(447, l17);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/resources/ResourcePackRepository");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "fileResourcepacks", "Ljava/io/File;");
        mv.visitTypeInsn(NEW, "java/io/File");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcDataDir", "Ljava/io/File;");
        mv.visitLdcInsn("server-resource-packs");
        mv.visitMethodInsn(INVOKESPECIAL, "java/io/File", "<init>", "(Ljava/io/File;Ljava/lang/String;)V", false);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcDefaultResourcePack", "Lnet/minecraft/client/resources/DefaultResourcePack;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "metadataSerializer_", "Lnet/minecraft/client/resources/data/IMetadataSerializer;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/resources/ResourcePackRepository", "<init>", "(Ljava/io/File;Ljava/io/File;Lnet/minecraft/client/resources/IResourcePack;Lnet/minecraft/client/resources/data/IMetadataSerializer;Lnet/minecraft/client/settings/GameSettings;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "mcResourcePackRepository", "Lnet/minecraft/client/resources/ResourcePackRepository;");
        Label l18 = new Label();
        mv.visitLabel(l18);
        mv.visitLineNumber(448, l18);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/resources/SimpleReloadableResourceManager");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "metadataSerializer_", "Lnet/minecraft/client/resources/data/IMetadataSerializer;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/resources/SimpleReloadableResourceManager", "<init>", "(Lnet/minecraft/client/resources/data/IMetadataSerializer;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        Label l19 = new Label();
        mv.visitLabel(l19);
        mv.visitLineNumber(449, l19);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/resources/LanguageManager");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "metadataSerializer_", "Lnet/minecraft/client/resources/data/IMetadataSerializer;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "language", "Ljava/lang/String;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/resources/LanguageManager", "<init>", "(Lnet/minecraft/client/resources/data/IMetadataSerializer;Ljava/lang/String;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "mcLanguageManager", "Lnet/minecraft/client/resources/LanguageManager;");
        Label l20 = new Label();
        mv.visitLabel(l20);
        mv.visitLineNumber(450, l20);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcLanguageManager", "Lnet/minecraft/client/resources/LanguageManager;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l21 = new Label();
        mv.visitLabel(l21);
        mv.visitLineNumber(451, l21);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/client/FMLClientHandler", "instance", "()Lnet/minecraftforge/fml/client/FMLClientHandler;", false);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "defaultResourcePacks", "Ljava/util/List;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/client/FMLClientHandler", "beginMinecraftLoading", "(Lnet/minecraft/client/Minecraft;Ljava/util/List;Lnet/minecraft/client/resources/IReloadableResourceManager;)V", false);
        Label l22 = new Label();
        mv.visitLabel(l22);
        mv.visitLineNumber(452, l22);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/renderer/texture/TextureManager");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/texture/TextureManager", "<init>", "(Lnet/minecraft/client/resources/IResourceManager;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        Label l23 = new Label();
        mv.visitLabel(l23);
        mv.visitLineNumber(453, l23);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l24 = new Label();
        mv.visitLabel(l24);
        mv.visitLineNumber(454, l24);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/client/SplashProgress", "drawVanillaScreen", "(Lnet/minecraft/client/renderer/texture/TextureManager;)V", false);
        Label l25 = new Label();
        mv.visitLabel(l25);
        mv.visitLineNumber(455, l25);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "initStream", "()V", false);
        Label l26 = new Label();
        mv.visitLabel(l26);
        mv.visitLineNumber(456, l26);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/resources/SkinManager");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitTypeInsn(NEW, "java/io/File");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "fileAssets", "Ljava/io/File;");
        mv.visitLdcInsn("skins");
        mv.visitMethodInsn(INVOKESPECIAL, "java/io/File", "<init>", "(Ljava/io/File;Ljava/lang/String;)V", false);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "sessionService", "Lcom/mojang/authlib/minecraft/MinecraftSessionService;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/resources/SkinManager", "<init>", "(Lnet/minecraft/client/renderer/texture/TextureManager;Ljava/io/File;Lcom/mojang/authlib/minecraft/MinecraftSessionService;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "skinManager", "Lnet/minecraft/client/resources/SkinManager;");
        Label l27 = new Label();
        mv.visitLabel(l27);
        mv.visitLineNumber(457, l27);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/world/chunk/storage/AnvilSaveConverter");
        mv.visitInsn(DUP);
        mv.visitTypeInsn(NEW, "java/io/File");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcDataDir", "Ljava/io/File;");
        mv.visitLdcInsn("saves");
        mv.visitMethodInsn(INVOKESPECIAL, "java/io/File", "<init>", "(Ljava/io/File;Ljava/lang/String;)V", false);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/world/chunk/storage/AnvilSaveConverter", "<init>", "(Ljava/io/File;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "saveLoader", "Lnet/minecraft/world/storage/ISaveFormat;");
        Label l28 = new Label();
        mv.visitLabel(l28);
        mv.visitLineNumber(458, l28);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/audio/SoundHandler");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/audio/SoundHandler", "<init>", "(Lnet/minecraft/client/resources/IResourceManager;Lnet/minecraft/client/settings/GameSettings;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "mcSoundHandler", "Lnet/minecraft/client/audio/SoundHandler;");
        Label l29 = new Label();
        mv.visitLabel(l29);
        mv.visitLineNumber(459, l29);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcSoundHandler", "Lnet/minecraft/client/audio/SoundHandler;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l30 = new Label();
        mv.visitLabel(l30);
        mv.visitLineNumber(460, l30);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/audio/MusicTicker");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/audio/MusicTicker", "<init>", "(Lnet/minecraft/client/Minecraft;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "mcMusicTicker", "Lnet/minecraft/client/audio/MusicTicker;");
        Label l31 = new Label();
        mv.visitLabel(l31);
        mv.visitLineNumber(461, l31);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/gui/FontRenderer");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitTypeInsn(NEW, "net/minecraft/util/ResourceLocation");
        mv.visitInsn(DUP);
        mv.visitLdcInsn("textures/font/ascii.png");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/ResourceLocation", "<init>", "(Ljava/lang/String;)V", false);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitInsn(ICONST_0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/gui/FontRenderer", "<init>", "(Lnet/minecraft/client/settings/GameSettings;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/client/renderer/texture/TextureManager;Z)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "fontRendererObj", "Lnet/minecraft/client/gui/FontRenderer;");
        Label l32 = new Label();
        mv.visitLabel(l32);
        mv.visitLineNumber(463, l32);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "language", "Ljava/lang/String;");
        Label l33 = new Label();
        mv.visitJumpInsn(IFNULL, l33);
        Label l34 = new Label();
        mv.visitLabel(l34);
        mv.visitLineNumber(465, l34);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "fontRendererObj", "Lnet/minecraft/client/gui/FontRenderer;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/Minecraft", "isUnicode", "()Z", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/gui/FontRenderer", "setUnicodeFlag", "(Z)V", false);
        Label l35 = new Label();
        mv.visitLabel(l35);
        mv.visitLineNumber(466, l35);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "fontRendererObj", "Lnet/minecraft/client/gui/FontRenderer;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcLanguageManager", "Lnet/minecraft/client/resources/LanguageManager;");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/resources/LanguageManager", "isCurrentLanguageBidirectional", "()Z", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/gui/FontRenderer", "setBidiFlag", "(Z)V", false);
        mv.visitLabel(l33);
        mv.visitLineNumber(469, l33);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/gui/FontRenderer");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitTypeInsn(NEW, "net/minecraft/util/ResourceLocation");
        mv.visitInsn(DUP);
        mv.visitLdcInsn("textures/font/ascii_sga.png");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/ResourceLocation", "<init>", "(Ljava/lang/String;)V", false);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitInsn(ICONST_0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/gui/FontRenderer", "<init>", "(Lnet/minecraft/client/settings/GameSettings;Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/client/renderer/texture/TextureManager;Z)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "standardGalacticFontRenderer", "Lnet/minecraft/client/gui/FontRenderer;");
        Label l36 = new Label();
        mv.visitLabel(l36);
        mv.visitLineNumber(470, l36);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "fontRendererObj", "Lnet/minecraft/client/gui/FontRenderer;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l37 = new Label();
        mv.visitLabel(l37);
        mv.visitLineNumber(471, l37);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "standardGalacticFontRenderer", "Lnet/minecraft/client/gui/FontRenderer;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l38 = new Label();
        mv.visitLabel(l38);
        mv.visitLineNumber(472, l38);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitTypeInsn(NEW, "net/minecraft/client/resources/GrassColorReloadListener");
        mv.visitInsn(DUP);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/resources/GrassColorReloadListener", "<init>", "()V", false);
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l39 = new Label();
        mv.visitLabel(l39);
        mv.visitLineNumber(473, l39);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitTypeInsn(NEW, "net/minecraft/client/resources/FoliageColorReloadListener");
        mv.visitInsn(DUP);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/resources/FoliageColorReloadListener", "<init>", "()V", false);
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l40 = new Label();
        mv.visitLabel(l40);
        mv.visitLineNumber(474, l40);
        mv.visitFieldInsn(GETSTATIC, "net/minecraft/stats/AchievementList", "openInventory", "Lnet/minecraft/stats/Achievement;");
        mv.visitTypeInsn(NEW, "net/minecraft/client/Minecraft$1");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft$1", "<init>", "(Lnet/minecraft/client/Minecraft;)V", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/stats/Achievement", "setStatStringFormatter", "(Lnet/minecraft/stats/IStatStringFormat;)Lnet/minecraft/stats/Achievement;", false);
        mv.visitInsn(POP);
        Label l41 = new Label();
        mv.visitLabel(l41);
        mv.visitLineNumber(491, l41);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/util/MouseHelper");
        mv.visitInsn(DUP);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/util/MouseHelper", "<init>", "()V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "mouseHelper", "Lnet/minecraft/util/MouseHelper;");
        Label l42 = new Label();
        mv.visitLabel(l42);
        mv.visitLineNumber(492, l42);
        mv.visitLdcInsn("Rendering Setup");
        mv.visitInsn(ICONST_5);
        mv.visitInsn(ICONST_1);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/common/ProgressManager", "push", "(Ljava/lang/String;IZ)Lnet/minecraftforge/fml/common/ProgressManager$ProgressBar;", false);
        mv.visitVarInsn(ASTORE, 1);
        Label l43 = new Label();
        mv.visitLabel(l43);
        mv.visitLineNumber(493, l43);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitLdcInsn("GL Setup");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/common/ProgressManager$ProgressBar", "step", "(Ljava/lang/String;)V", false);
        Label l44 = new Label();
        mv.visitLabel(l44);
        mv.visitLineNumber(494, l44);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitLdcInsn("Pre startup");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "checkGLError", "(Ljava/lang/String;)V", false);
        Label l45 = new Label();
        mv.visitLabel(l45);
        mv.visitLineNumber(495, l45);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "enableTexture2D", "()V", false);
        Label l46 = new Label();
        mv.visitLabel(l46);
        mv.visitLineNumber(496, l46);
        mv.visitIntInsn(SIPUSH, 7425);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "shadeModel", "(I)V", false);
        Label l47 = new Label();
        mv.visitLabel(l47);
        mv.visitLineNumber(497, l47);
        mv.visitInsn(DCONST_1);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "clearDepth", "(D)V", false);
        Label l48 = new Label();
        mv.visitLabel(l48);
        mv.visitLineNumber(498, l48);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "enableDepth", "()V", false);
        Label l49 = new Label();
        mv.visitLabel(l49);
        mv.visitLineNumber(499, l49);
        mv.visitIntInsn(SIPUSH, 515);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "depthFunc", "(I)V", false);
        Label l50 = new Label();
        mv.visitLabel(l50);
        mv.visitLineNumber(500, l50);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "enableAlpha", "()V", false);
        Label l51 = new Label();
        mv.visitLabel(l51);
        mv.visitLineNumber(501, l51);
        mv.visitIntInsn(SIPUSH, 516);
        mv.visitLdcInsn(new Float("0.1"));
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "alphaFunc", "(IF)V", false);
        Label l52 = new Label();
        mv.visitLabel(l52);
        mv.visitLineNumber(502, l52);
        mv.visitIntInsn(SIPUSH, 1029);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "cullFace", "(I)V", false);
        Label l53 = new Label();
        mv.visitLabel(l53);
        mv.visitLineNumber(503, l53);
        mv.visitIntInsn(SIPUSH, 5889);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "matrixMode", "(I)V", false);
        Label l54 = new Label();
        mv.visitLabel(l54);
        mv.visitLineNumber(504, l54);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "loadIdentity", "()V", false);
        Label l55 = new Label();
        mv.visitLabel(l55);
        mv.visitLineNumber(505, l55);
        mv.visitIntInsn(SIPUSH, 5888);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "matrixMode", "(I)V", false);
        Label l56 = new Label();
        mv.visitLabel(l56);
        mv.visitLineNumber(506, l56);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitLdcInsn("Startup");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "checkGLError", "(Ljava/lang/String;)V", false);
        Label l57 = new Label();
        mv.visitLabel(l57);
        mv.visitLineNumber(507, l57);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitLdcInsn("Loading Texture Map");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/common/ProgressManager$ProgressBar", "step", "(Ljava/lang/String;)V", false);
        Label l58 = new Label();
        mv.visitLabel(l58);
        mv.visitLineNumber(508, l58);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/renderer/texture/TextureMap");
        mv.visitInsn(DUP);
        mv.visitLdcInsn("textures");
        mv.visitInsn(ICONST_1);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/texture/TextureMap", "<init>", "(Ljava/lang/String;Z)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "textureMapBlocks", "Lnet/minecraft/client/renderer/texture/TextureMap;");
        Label l59 = new Label();
        mv.visitLabel(l59);
        mv.visitLineNumber(509, l59);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "textureMapBlocks", "Lnet/minecraft/client/renderer/texture/TextureMap;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "mipmapLevels", "I");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureMap", "setMipmapLevels", "(I)V", false);
        Label l60 = new Label();
        mv.visitLabel(l60);
        mv.visitLineNumber(510, l60);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitFieldInsn(GETSTATIC, "net/minecraft/client/renderer/texture/TextureMap", "locationBlocksTexture", "Lnet/minecraft/util/ResourceLocation;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "textureMapBlocks", "Lnet/minecraft/client/renderer/texture/TextureMap;");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "loadTickableTexture", "(Lnet/minecraft/util/ResourceLocation;Lnet/minecraft/client/renderer/texture/ITickableTextureObject;)Z", false);
        mv.visitInsn(POP);
        Label l61 = new Label();
        mv.visitLabel(l61);
        mv.visitLineNumber(511, l61);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitFieldInsn(GETSTATIC, "net/minecraft/client/renderer/texture/TextureMap", "locationBlocksTexture", "Lnet/minecraft/util/ResourceLocation;");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureManager", "bindTexture", "(Lnet/minecraft/util/ResourceLocation;)V", false);
        Label l62 = new Label();
        mv.visitLabel(l62);
        mv.visitLineNumber(512, l62);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "textureMapBlocks", "Lnet/minecraft/client/renderer/texture/TextureMap;");
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "mipmapLevels", "I");
        Label l63 = new Label();
        mv.visitJumpInsn(IFLE, l63);
        mv.visitInsn(ICONST_1);
        Label l64 = new Label();
        mv.visitJumpInsn(GOTO, l64);
        mv.visitLabel(l63);
        mv.visitFrame(Opcodes.F_FULL, 2, new Object[] {"net/minecraft/client/Minecraft", "net/minecraftforge/fml/common/ProgressManager$ProgressBar"}, 2, new Object[] {"net/minecraft/client/renderer/texture/TextureMap", Opcodes.INTEGER});
        mv.visitInsn(ICONST_0);
        mv.visitLabel(l64);
        mv.visitFrame(Opcodes.F_FULL, 2, new Object[] {"net/minecraft/client/Minecraft", "net/minecraftforge/fml/common/ProgressManager$ProgressBar"}, 3, new Object[] {"net/minecraft/client/renderer/texture/TextureMap", Opcodes.INTEGER, Opcodes.INTEGER});
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/texture/TextureMap", "setBlurMipmapDirect", "(ZZ)V", false);
        Label l65 = new Label();
        mv.visitLabel(l65);
        mv.visitLineNumber(513, l65);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitLdcInsn("Loading Model Manager");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/common/ProgressManager$ProgressBar", "step", "(Ljava/lang/String;)V", false);
        Label l66 = new Label();
        mv.visitLabel(l66);
        mv.visitLineNumber(514, l66);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/resources/model/ModelManager");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "textureMapBlocks", "Lnet/minecraft/client/renderer/texture/TextureMap;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/resources/model/ModelManager", "<init>", "(Lnet/minecraft/client/renderer/texture/TextureMap;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "modelManager", "Lnet/minecraft/client/resources/model/ModelManager;");
        Label l67 = new Label();
        mv.visitLabel(l67);
        mv.visitLineNumber(515, l67);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "modelManager", "Lnet/minecraft/client/resources/model/ModelManager;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l68 = new Label();
        mv.visitLabel(l68);
        mv.visitLineNumber(516, l68);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitLdcInsn("Loading Item Renderer");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/common/ProgressManager$ProgressBar", "step", "(Ljava/lang/String;)V", false);
        Label l69 = new Label();
        mv.visitLabel(l69);
        mv.visitLineNumber(517, l69);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/renderer/entity/RenderItem");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "modelManager", "Lnet/minecraft/client/resources/model/ModelManager;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/entity/RenderItem", "<init>", "(Lnet/minecraft/client/renderer/texture/TextureManager;Lnet/minecraft/client/resources/model/ModelManager;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "renderItem", "Lnet/minecraft/client/renderer/entity/RenderItem;");
        Label l70 = new Label();
        mv.visitLabel(l70);
        mv.visitLineNumber(518, l70);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/renderer/entity/RenderManager");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderItem", "Lnet/minecraft/client/renderer/entity/RenderItem;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/entity/RenderManager", "<init>", "(Lnet/minecraft/client/renderer/texture/TextureManager;Lnet/minecraft/client/renderer/entity/RenderItem;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "renderManager", "Lnet/minecraft/client/renderer/entity/RenderManager;");
        Label l71 = new Label();
        mv.visitLabel(l71);
        mv.visitLineNumber(519, l71);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/renderer/ItemRenderer");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/ItemRenderer", "<init>", "(Lnet/minecraft/client/Minecraft;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "itemRenderer", "Lnet/minecraft/client/renderer/ItemRenderer;");
        Label l72 = new Label();
        mv.visitLabel(l72);
        mv.visitLineNumber(520, l72);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderItem", "Lnet/minecraft/client/renderer/entity/RenderItem;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l73 = new Label();
        mv.visitLabel(l73);
        mv.visitLineNumber(521, l73);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitLdcInsn("Loading Entity Renderer");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/common/ProgressManager$ProgressBar", "step", "(Ljava/lang/String;)V", false);
        Label l74 = new Label();
        mv.visitLabel(l74);
        mv.visitLineNumber(522, l74);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/renderer/EntityRenderer");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/EntityRenderer", "<init>", "(Lnet/minecraft/client/Minecraft;Lnet/minecraft/client/resources/IResourceManager;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "entityRenderer", "Lnet/minecraft/client/renderer/EntityRenderer;");
        Label l75 = new Label();
        mv.visitLabel(l75);
        mv.visitLineNumber(523, l75);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "entityRenderer", "Lnet/minecraft/client/renderer/EntityRenderer;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l76 = new Label();
        mv.visitLabel(l76);
        mv.visitLineNumber(524, l76);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/renderer/BlockRendererDispatcher");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "modelManager", "Lnet/minecraft/client/resources/model/ModelManager;");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/resources/model/ModelManager", "getBlockModelShapes", "()Lnet/minecraft/client/renderer/BlockModelShapes;", false);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/renderer/BlockRendererDispatcher", "<init>", "(Lnet/minecraft/client/renderer/BlockModelShapes;Lnet/minecraft/client/settings/GameSettings;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "blockRenderDispatcher", "Lnet/minecraft/client/renderer/BlockRendererDispatcher;");
        Label l77 = new Label();
        mv.visitLabel(l77);
        mv.visitLineNumber(525, l77);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "blockRenderDispatcher", "Lnet/minecraft/client/renderer/BlockRendererDispatcher;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l78 = new Label();
        mv.visitLabel(l78);
        mv.visitLineNumber(526, l78);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "com/continuum/nova/replacements/NativeRenderGlobal");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "com/continuum/nova/replacements/NativeRenderGlobal", "<init>", "(Lnet/minecraft/client/Minecraft;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "renderGlobal", "Lnet/minecraft/client/renderer/RenderGlobal;");
        Label l79 = new Label();
        mv.visitLabel(l79);
        mv.visitLineNumber(527, l79);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mcResourceManager", "Lnet/minecraft/client/resources/IReloadableResourceManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderGlobal", "Lnet/minecraft/client/renderer/RenderGlobal;");
        mv.visitMethodInsn(INVOKEINTERFACE, "net/minecraft/client/resources/IReloadableResourceManager", "registerReloadListener", "(Lnet/minecraft/client/resources/IResourceManagerReloadListener;)V", true);
        Label l80 = new Label();
        mv.visitLabel(l80);
        mv.visitLineNumber(528, l80);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/gui/achievement/GuiAchievement");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/gui/achievement/GuiAchievement", "<init>", "(Lnet/minecraft/client/Minecraft;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "guiAchievement", "Lnet/minecraft/client/gui/achievement/GuiAchievement;");
        Label l81 = new Label();
        mv.visitLabel(l81);
        mv.visitLineNumber(529, l81);
        mv.visitInsn(ICONST_0);
        mv.visitInsn(ICONST_0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "displayWidth", "I");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "displayHeight", "I");
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraft/client/renderer/GlStateManager", "viewport", "(IIII)V", false);
        Label l82 = new Label();
        mv.visitLabel(l82);
        mv.visitLineNumber(530, l82);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/particle/EffectRenderer");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "theWorld", "Lnet/minecraft/client/multiplayer/WorldClient;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/particle/EffectRenderer", "<init>", "(Lnet/minecraft/world/World;Lnet/minecraft/client/renderer/texture/TextureManager;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "effectRenderer", "Lnet/minecraft/client/particle/EffectRenderer;");
        Label l83 = new Label();
        mv.visitLabel(l83);
        mv.visitLineNumber(531, l83);
        mv.visitVarInsn(ALOAD, 1);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/common/ProgressManager", "pop", "(Lnet/minecraftforge/fml/common/ProgressManager$ProgressBar;)V", false);
        Label l84 = new Label();
        mv.visitLabel(l84);
        mv.visitLineNumber(532, l84);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/client/FMLClientHandler", "instance", "()Lnet/minecraftforge/fml/client/FMLClientHandler;", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/client/FMLClientHandler", "finishMinecraftLoading", "()V", false);
        Label l85 = new Label();
        mv.visitLabel(l85);
        mv.visitLineNumber(533, l85);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitLdcInsn("Post startup");
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/Minecraft", "checkGLError", "(Ljava/lang/String;)V", false);
        Label l86 = new Label();
        mv.visitLabel(l86);
        mv.visitLineNumber(534, l86);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraftforge/client/GuiIngameForge");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraftforge/client/GuiIngameForge", "<init>", "(Lnet/minecraft/client/Minecraft;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "ingameGUI", "Lnet/minecraft/client/gui/GuiIngame;");
        Label l87 = new Label();
        mv.visitLabel(l87);
        mv.visitLineNumber(536, l87);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "serverName", "Ljava/lang/String;");
        Label l88 = new Label();
        mv.visitJumpInsn(IFNULL, l88);
        Label l89 = new Label();
        mv.visitLabel(l89);
        mv.visitLineNumber(538, l89);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/client/FMLClientHandler", "instance", "()Lnet/minecraftforge/fml/client/FMLClientHandler;", false);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "serverName", "Ljava/lang/String;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "serverPort", "I");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/client/FMLClientHandler", "connectToServerAtStartup", "(Ljava/lang/String;I)V", false);
        Label l90 = new Label();
        mv.visitJumpInsn(GOTO, l90);
        mv.visitLabel(l88);
        mv.visitLineNumber(542, l88);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/gui/GuiMainMenu");
        mv.visitInsn(DUP);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/gui/GuiMainMenu", "<init>", "()V", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/Minecraft", "displayGuiScreen", "(Lnet/minecraft/client/gui/GuiScreen;)V", false);
        mv.visitLabel(l90);
        mv.visitLineNumber(545, l90);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderEngine", "Lnet/minecraft/client/renderer/texture/TextureManager;");
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "mojangLogo", "Lnet/minecraft/util/ResourceLocation;");
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/client/SplashProgress", "clearVanillaResources", "(Lnet/minecraft/client/renderer/texture/TextureManager;Lnet/minecraft/util/ResourceLocation;)V", false);
        Label l91 = new Label();
        mv.visitLabel(l91);
        mv.visitLineNumber(546, l91);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitInsn(ACONST_NULL);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "mojangLogo", "Lnet/minecraft/util/ResourceLocation;");
        Label l92 = new Label();
        mv.visitLabel(l92);
        mv.visitLineNumber(547, l92);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitTypeInsn(NEW, "net/minecraft/client/LoadingScreenRenderer");
        mv.visitInsn(DUP);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKESPECIAL, "net/minecraft/client/LoadingScreenRenderer", "<init>", "(Lnet/minecraft/client/Minecraft;)V", false);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/Minecraft", "loadingScreen", "Lnet/minecraft/client/LoadingScreenRenderer;");
        Label l93 = new Label();
        mv.visitLabel(l93);
        mv.visitLineNumber(549, l93);
        mv.visitMethodInsn(INVOKESTATIC, "net/minecraftforge/fml/client/FMLClientHandler", "instance", "()Lnet/minecraftforge/fml/client/FMLClientHandler;", false);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraftforge/fml/client/FMLClientHandler", "onInitializationComplete", "()V", false);
        Label l94 = new Label();
        mv.visitLabel(l94);
        mv.visitLineNumber(550, l94);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "fullScreen", "Z");
        mv.visitJumpInsn(IFEQ, l0);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "fullscreen", "Z");
        mv.visitJumpInsn(IFNE, l0);
        Label l95 = new Label();
        mv.visitLabel(l95);
        mv.visitLineNumber(552, l95);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/Minecraft", "toggleFullscreen", "()V", false);
        mv.visitLabel(l0);
        mv.visitLineNumber(557, l0);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/settings/GameSettings", "enableVsync", "Z");
        mv.visitMethodInsn(INVOKESTATIC, "org/lwjgl/opengl/Display", "setVSyncEnabled", "(Z)V", false);
        mv.visitLabel(l1);
        mv.visitLineNumber(563, l1);
        Label l96 = new Label();
        mv.visitJumpInsn(GOTO, l96);
        mv.visitLabel(l2);
        mv.visitLineNumber(559, l2);
        mv.visitFrame(Opcodes.F_SAME1, 0, null, 1, new Object[] {"org/lwjgl/opengl/OpenGLException"});
        mv.visitVarInsn(ASTORE, 2);
        Label l97 = new Label();
        mv.visitLabel(l97);
        mv.visitLineNumber(561, l97);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitInsn(ICONST_0);
        mv.visitFieldInsn(PUTFIELD, "net/minecraft/client/settings/GameSettings", "enableVsync", "Z");
        Label l98 = new Label();
        mv.visitLabel(l98);
        mv.visitLineNumber(562, l98);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "gameSettings", "Lnet/minecraft/client/settings/GameSettings;");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/settings/GameSettings", "saveOptions", "()V", false);
        mv.visitLabel(l96);
        mv.visitLineNumber(565, l96);
        mv.visitFrame(Opcodes.F_SAME, 0, null, 0, null);
        mv.visitVarInsn(ALOAD, 0);
        mv.visitFieldInsn(GETFIELD, "net/minecraft/client/Minecraft", "renderGlobal", "Lnet/minecraft/client/renderer/RenderGlobal;");
        mv.visitMethodInsn(INVOKEVIRTUAL, "net/minecraft/client/renderer/RenderGlobal", "makeEntityOutlineShader", "()V", false);
        Label l99 = new Label();
        mv.visitLabel(l99);
        mv.visitLineNumber(566, l99);
        mv.visitInsn(RETURN);
        Label l100 = new Label();
        mv.visitLabel(l100);
        mv.visitLocalVariable("var2", "Lorg/lwjgl/opengl/OpenGLException;", null, l97, l96, 2);
        mv.visitLocalVariable("this", "Lnet/minecraft/client/Minecraft;", null, l3, l100, 0);
        mv.visitLocalVariable("bar", "Lnet/minecraftforge/fml/common/ProgressManager$ProgressBar;", null, l43, l100, 1);
        mv.visitMaxs(8, 3);
    }
}
