include(CheckCXXCompilerFlag)

macro(target_compile_options_if_supported target private_or_public)
    foreach(option ${ARGN})
        set(${CMAKE_CXX_COMPILER_ID}_SUPPORTS_${option})
        check_cxx_compiler_flag(${option} ${CMAKE_CXX_COMPILER_ID}_SUPPORTS_${option})
        if(${CMAKE_CXX_COMPILER_ID}_SUPPORTS_${option})
            target_compile_options(${target} ${private_or_public} ${option})
        endif()
    endforeach()
endmacro()

macro(add_compile_options_if_supported)
    foreach(option ${ARGN})
        set(${CMAKE_CXX_COMPILER_ID}_SUPPORTS_${option})
        check_cxx_compiler_flag(${option} ${CMAKE_CXX_COMPILER_ID}_SUPPORTS_${option})
        if(${CMAKE_CXX_COMPILER_ID}_SUPPORTS_${option})
            add_compile_options(${option})
        endif()
    endforeach()
endmacro()