/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ddubois' at '8/11/16 7:57 PM' with Gradle 2.14.1
 *
 * @author ddubois, @date 8/11/16 7:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
