/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_continuum_vulkan_nativethread_NativeInterface */

#ifndef _Included_com_continuum_vulkan_nativethread_NativeInterface
#define _Included_com_continuum_vulkan_nativethread_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_continuum_vulkan_nativethread_NativeInterface
 * Method:    runVulkanMod
 * Signature: ()V
 */
JNIEXPORT jlong JNICALL Java_com_continuum_vulkan_nativethread_NativeInterface_runVulkanMod
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
