/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_continuum_nova_nativethread_NativeInterface */

#ifndef _Included_com_continuum_nova_nativethread_NativeInterface
#define _Included_com_continuum_nova_nativethread_NativeInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_continuum_nova_nativethread_NativeInterface
 * Method:    runVulkanMod
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_continuum_nova_nativethread_NativeInterface_runVulkanMod
  (JNIEnv *, jobject);

/*
 * Class:     com_continuum_nova_nativethread_NativeInterface
 * Method:    setWorld
 * Signature: (Lnet/minecraft/world/World;)V
 */
JNIEXPORT void JNICALL Java_com_continuum_nova_nativethread_NativeInterface_setWorld
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
