/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_continuum_nova_replacements_NativeRenderGlobal */

#ifndef _Included_com_continuum_nova_replacements_NativeRenderGlobal
#define _Included_com_continuum_nova_replacements_NativeRenderGlobal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_continuum_nova_replacements_NativeRenderGlobal
 * Method:    setWorldClient
 * Signature: (Lnet/minecraft/client/multiplayer/WorldClient;)V
 */
JNIEXPORT void JNICALL Java_com_continuum_nova_replacements_NativeRenderGlobal_setWorldClient
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
