// FILE: C:/Users/David/Documents/MC/force-src/src/main/native/vulkan_mod/renderer.cpp

#include "renderer.h"

namespace vulkan_mod {


    /** 
     *  Class that handles actually drawing things onscreen. May or may not change to a namespace
     */


    // Operations


/** 
     *  Renders the current scene
     */
void renderer::render_scene()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B87 begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B87 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace vulkan_mod */
