// FILE: C:/Users/David/Documents/MC/force-src/src/main/native/vulkan_mod/render_data_store.cpp

#include "render_data_store.h"

namespace vulkan_mod {



    // Operations


/** 
     *  Updates the given chunk by finding the chunk with the given id (or creating it if it doesn't exist), then copying the data from the given mc_chunk into the old one
     */
void render_data_store::update_chunk(mc_chunk new_chunk)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B76 begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B76 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Updates the given entity by finding the entity with the given ID (or creating it if it doesn't already exist) and copying the new entity into the old one
     */
void render_data_store::update_entity(mc_entity new_entity)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B7B begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B7B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Returns all chunks. Simple as that.
     */
store render_data_store::get_all_chunks()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B7F begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B7F end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element


/** 
     *  Returns all entities
     */
store render_data_store::get_all_entities()
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B82 begin
{
}
// section -64--88-1-3-626d7542:152506aa714:-8000:0000000000000B82 end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace vulkan_mod */
