// FILE: C:/Users/David/Documents/MC/force-src/src/main/native/vulkan_mod/store.cpp

#include "store.h"

namespace vulkan_mod {


    /* {deprecated=false}*/


    // Operations

void store::add_item(T item)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3--3f1832a6:1524b8a6547:-8000:0000000000000A8B begin
{
}
// section -64--88-1-3--3f1832a6:1524b8a6547:-8000:0000000000000A8B end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

void store::remove_item(void  id : int)
// don't delete the following line as it's needed to preserve source code of this autogenerated element
// section -64--88-1-3--3f1832a6:1524b8a6547:-8000:0000000000000A8E begin
{
}
// section -64--88-1-3--3f1832a6:1524b8a6547:-8000:0000000000000A8E end
// don't delete the previous line as it's needed to preserve source code of this autogenerated element

} /* End of namespace vulkan_mod */
