/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_continuum_nova_system_NovaNative_mc_chunk_render_object */

#ifndef _Included_com_continuum_nova_system_NovaNative_mc_chunk_render_object
#define _Included_com_continuum_nova_system_NovaNative_mc_chunk_render_object
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
