/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_continuum_nova_system_NovaNative_NativeBoolean */

#ifndef _Included_com_continuum_nova_system_NovaNative_NativeBoolean
#define _Included_com_continuum_nova_system_NovaNative_NativeBoolean
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
