/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_continuum_nova_system_NovaNative_mouse_scroll_event */

#ifndef _Included_com_continuum_nova_system_NovaNative_mouse_scroll_event
#define _Included_com_continuum_nova_system_NovaNative_mouse_scroll_event
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
