package net.minecraft.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;

public class SoundEvents
{
    public static final SoundEvent ambient_cave;
    public static final SoundEvent block_anvil_break;
    public static final SoundEvent block_anvil_destroy;
    public static final SoundEvent block_anvil_fall;
    public static final SoundEvent block_anvil_hit;
    public static final SoundEvent block_anvil_land;
    public static final SoundEvent block_anvil_place;
    public static final SoundEvent block_anvil_step;
    public static final SoundEvent block_anvil_use;
    public static final SoundEvent entity_armorstand_break;
    public static final SoundEvent entity_armorstand_fall;
    public static final SoundEvent entity_armorstand_hit;
    public static final SoundEvent entity_armorstand_place;
    public static final SoundEvent item_armor_equip_chain;
    public static final SoundEvent item_armor_equip_diamond;
    public static final SoundEvent item_armor_equip_generic;
    public static final SoundEvent item_armor_equip_gold;
    public static final SoundEvent item_armor_equip_iron;
    public static final SoundEvent item_armor_equip_leather;
    public static final SoundEvent entity_arrow_hit;
    public static final SoundEvent entity_arrow_hit_player;
    public static final SoundEvent entity_arrow_shoot;
    public static final SoundEvent entity_bat_ambient;
    public static final SoundEvent entity_bat_death;
    public static final SoundEvent entity_bat_hurt;
    public static final SoundEvent entity_bat_loop;
    public static final SoundEvent entity_bat_takeoff;
    public static final SoundEvent entity_blaze_ambient;
    public static final SoundEvent entity_blaze_burn;
    public static final SoundEvent entity_blaze_death;
    public static final SoundEvent entity_blaze_hurt;
    public static final SoundEvent entity_blaze_shoot;
    public static final SoundEvent entity_bobber_splash;
    public static final SoundEvent entity_bobber_throw;
    public static final SoundEvent item_bottle_fill;
    public static final SoundEvent item_bottle_fill_dragonbreath;
    public static final SoundEvent block_brewing_stand_brew;
    public static final SoundEvent item_bucket_empty;
    public static final SoundEvent item_bucket_empty_lava;
    public static final SoundEvent item_bucket_fill;
    public static final SoundEvent item_bucket_fill_lava;
    public static final SoundEvent entity_cat_ambient;
    public static final SoundEvent entity_cat_death;
    public static final SoundEvent entity_cat_hiss;
    public static final SoundEvent entity_cat_hurt;
    public static final SoundEvent entity_cat_purr;
    public static final SoundEvent entity_cat_purreow;
    public static final SoundEvent block_chest_close;
    public static final SoundEvent block_chest_locked;
    public static final SoundEvent block_chest_open;
    public static final SoundEvent entity_chicken_ambient;
    public static final SoundEvent entity_chicken_death;
    public static final SoundEvent entity_chicken_egg;
    public static final SoundEvent entity_chicken_hurt;
    public static final SoundEvent entity_chicken_step;
    public static final SoundEvent block_chorus_flower_death;
    public static final SoundEvent block_chorus_flower_grow;
    public static final SoundEvent item_chorus_fruit_teleport;
    public static final SoundEvent block_cloth_break;
    public static final SoundEvent block_cloth_fall;
    public static final SoundEvent block_cloth_hit;
    public static final SoundEvent block_cloth_place;
    public static final SoundEvent block_cloth_step;
    public static final SoundEvent block_comparator_click;
    public static final SoundEvent entity_cow_ambient;
    public static final SoundEvent entity_cow_death;
    public static final SoundEvent entity_cow_hurt;
    public static final SoundEvent entity_cow_milk;
    public static final SoundEvent entity_cow_step;
    public static final SoundEvent entity_creeper_death;
    public static final SoundEvent entity_creeper_hurt;
    public static final SoundEvent entity_creeper_primed;
    public static final SoundEvent block_dispenser_dispense;
    public static final SoundEvent block_dispenser_fail;
    public static final SoundEvent block_dispenser_launch;
    public static final SoundEvent entity_donkey_ambient;
    public static final SoundEvent entity_donkey_angry;
    public static final SoundEvent entity_donkey_chest;
    public static final SoundEvent entity_donkey_death;
    public static final SoundEvent entity_donkey_hurt;
    public static final SoundEvent entity_egg_throw;
    public static final SoundEvent entity_elder_guardian_ambient;
    public static final SoundEvent entity_elderguardian_ambientland;
    public static final SoundEvent entity_elder_guardian_curse;
    public static final SoundEvent entity_elder_guardian_death;
    public static final SoundEvent entity_elder_guardian_death_land;
    public static final SoundEvent entity_elder_guardian_hurt;
    public static final SoundEvent entity_elder_guardian_hurt_land;
    public static final SoundEvent block_enderchest_close;
    public static final SoundEvent block_enderchest_open;
    public static final SoundEvent entity_enderdragon_ambient;
    public static final SoundEvent entity_enderdragon_death;
    public static final SoundEvent entity_enderdragon_fireball_epld;
    public static final SoundEvent entity_enderdragon_flap;
    public static final SoundEvent entity_enderdragon_growl;
    public static final SoundEvent entity_enderdragon_hurt;
    public static final SoundEvent entity_enderdragon_shoot;
    public static final SoundEvent entity_endereye_launch;
    public static final SoundEvent entity_endermen_ambient;
    public static final SoundEvent entity_endermen_death;
    public static final SoundEvent entity_endermen_hurt;
    public static final SoundEvent entity_endermen_scream;
    public static final SoundEvent entity_endermen_stare;
    public static final SoundEvent entity_endermen_teleport;
    public static final SoundEvent entity_endermite_ambient;
    public static final SoundEvent entity_endermite_death;
    public static final SoundEvent entity_endermite_hurt;
    public static final SoundEvent entity_endermite_step;
    public static final SoundEvent entity_enderpearl_throw;
    public static final SoundEvent block_end_gateway_spawn;
    public static final SoundEvent entity_experience_bottle_throw;
    public static final SoundEvent entity_experience_orb_pickup;
    public static final SoundEvent entity_experience_orb_touch;
    public static final SoundEvent block_fence_gate_close;
    public static final SoundEvent block_fence_gate_open;
    public static final SoundEvent item_firecharge_use;
    public static final SoundEvent entity_firework_blast;
    public static final SoundEvent entity_firework_blast_far;
    public static final SoundEvent entity_firework_large_blast;
    public static final SoundEvent entity_firework_large_blast_far;
    public static final SoundEvent entity_firework_launch;
    public static final SoundEvent entity_firework_shoot;
    public static final SoundEvent entity_firework_twinkle;
    public static final SoundEvent entity_firework_twinkle_far;
    public static final SoundEvent block_fire_ambient;
    public static final SoundEvent block_fire_extinguish;
    public static final SoundEvent item_flintandsteel_use;
    public static final SoundEvent block_furnace_fire_crackle;
    public static final SoundEvent entity_generic_big_fall;
    public static final SoundEvent entity_generic_burn;
    public static final SoundEvent entity_generic_death;
    public static final SoundEvent entity_generic_drink;
    public static final SoundEvent entity_generic_eat;
    public static final SoundEvent entity_generic_explode;
    public static final SoundEvent entity_generic_extinguish_fire;
    public static final SoundEvent entity_generic_hurt;
    public static final SoundEvent entity_generic_small_fall;
    public static final SoundEvent entity_generic_splash;
    public static final SoundEvent entity_generic_swim;
    public static final SoundEvent entity_ghast_ambient;
    public static final SoundEvent entity_ghast_death;
    public static final SoundEvent entity_ghast_hurt;
    public static final SoundEvent entity_ghast_scream;
    public static final SoundEvent entity_ghast_shoot;
    public static final SoundEvent entity_ghast_warn;
    public static final SoundEvent block_glass_break;
    public static final SoundEvent block_glass_fall;
    public static final SoundEvent block_glass_hit;
    public static final SoundEvent block_glass_place;
    public static final SoundEvent block_glass_step;
    public static final SoundEvent block_grass_break;
    public static final SoundEvent block_grass_fall;
    public static final SoundEvent block_grass_hit;
    public static final SoundEvent block_grass_place;
    public static final SoundEvent block_grass_step;
    public static final SoundEvent block_gravel_break;
    public static final SoundEvent block_gravel_fall;
    public static final SoundEvent block_gravel_hit;
    public static final SoundEvent block_gravel_place;
    public static final SoundEvent block_gravel_step;
    public static final SoundEvent entity_guardian_ambient;
    public static final SoundEvent entity_guardian_ambient_land;
    public static final SoundEvent entity_guardian_attack;
    public static final SoundEvent entity_guardian_death;
    public static final SoundEvent entity_guardian_death_land;
    public static final SoundEvent entity_guardian_flop;
    public static final SoundEvent entity_guardian_hurt;
    public static final SoundEvent entity_guardian_hurt_land;
    public static final SoundEvent item_hoe_till;
    public static final SoundEvent entity_horse_ambient;
    public static final SoundEvent entity_horse_angry;
    public static final SoundEvent entity_horse_armor;
    public static final SoundEvent entity_horse_breathe;
    public static final SoundEvent entity_horse_death;
    public static final SoundEvent entity_horse_eat;
    public static final SoundEvent entity_horse_gallop;
    public static final SoundEvent entity_horse_hurt;
    public static final SoundEvent entity_horse_jump;
    public static final SoundEvent entity_horse_land;
    public static final SoundEvent entity_horse_saddle;
    public static final SoundEvent entity_horse_step;
    public static final SoundEvent entity_horse_step_wood;
    public static final SoundEvent entity_hostile_big_fall;
    public static final SoundEvent entity_hostile_death;
    public static final SoundEvent entity_hostile_hurt;
    public static final SoundEvent entity_hostile_small_fall;
    public static final SoundEvent entity_hostile_splash;
    public static final SoundEvent entity_hostile_swim;
    public static final SoundEvent entity_irongolem_attack;
    public static final SoundEvent entity_irongolem_death;
    public static final SoundEvent entity_irongolem_hurt;
    public static final SoundEvent entity_irongolem_step;
    public static final SoundEvent block_iron_door_close;
    public static final SoundEvent block_iron_door_open;
    public static final SoundEvent block_iron_trapdoor_close;
    public static final SoundEvent block_iron_trapdoor_open;
    public static final SoundEvent entity_itemframe_add_item;
    public static final SoundEvent entity_itemframe_break;
    public static final SoundEvent entity_itemframe_place;
    public static final SoundEvent entity_itemframe_remove_item;
    public static final SoundEvent entity_itemframe_rotate_item;
    public static final SoundEvent entity_item_break;
    public static final SoundEvent entity_item_pickup;
    public static final SoundEvent block_ladder_break;
    public static final SoundEvent block_ladder_fall;
    public static final SoundEvent block_ladder_hit;
    public static final SoundEvent block_ladder_place;
    public static final SoundEvent block_ladder_step;
    public static final SoundEvent block_lava_ambient;
    public static final SoundEvent block_lava_extinguish;
    public static final SoundEvent block_lava_pop;
    public static final SoundEvent entity_leashknot_break;
    public static final SoundEvent entity_leashknot_place;
    public static final SoundEvent block_lever_click;
    public static final SoundEvent entity_lightning_impact;
    public static final SoundEvent entity_lightning_thunder;
    public static final SoundEvent entity_lingeringpotion_throw;
    public static final SoundEvent entity_magmacube_death;
    public static final SoundEvent entity_magmacube_hurt;
    public static final SoundEvent entity_magmacube_jump;
    public static final SoundEvent entity_magmacube_squish;
    public static final SoundEvent block_metal_break;
    public static final SoundEvent block_metal_fall;
    public static final SoundEvent block_metal_hit;
    public static final SoundEvent block_metal_place;
    public static final SoundEvent block_metal_pressplate_click_off;
    public static final SoundEvent block_metal_pressplate_click_on;
    public static final SoundEvent block_metal_step;
    public static final SoundEvent entity_minecart_inside;
    public static final SoundEvent entity_minecart_riding;
    public static final SoundEvent entity_mooshroom_shear;
    public static final SoundEvent entity_mule_ambient;
    public static final SoundEvent entity_mule_death;
    public static final SoundEvent entity_mule_hurt;
    public static final SoundEvent music_creative;
    public static final SoundEvent music_credits;
    public static final SoundEvent music_dragon;
    public static final SoundEvent music_end;
    public static final SoundEvent music_game;
    public static final SoundEvent music_menu;
    public static final SoundEvent music_nether;
    public static final SoundEvent block_note_basedrum;
    public static final SoundEvent block_note_bass;
    public static final SoundEvent block_note_harp;
    public static final SoundEvent block_note_hat;
    public static final SoundEvent block_note_pling;
    public static final SoundEvent block_note_snare;
    public static final SoundEvent entity_painting_break;
    public static final SoundEvent entity_painting_place;
    public static final SoundEvent entity_pig_ambient;
    public static final SoundEvent entity_pig_death;
    public static final SoundEvent entity_pig_hurt;
    public static final SoundEvent entity_pig_saddle;
    public static final SoundEvent entity_pig_step;
    public static final SoundEvent block_piston_contract;
    public static final SoundEvent block_piston_extend;
    public static final SoundEvent entity_player_attack_crit;
    public static final SoundEvent entity_player_attack_knockback;
    public static final SoundEvent entity_player_attack_nodamage;
    public static final SoundEvent entity_player_attack_strong;
    public static final SoundEvent entity_player_attack_sweep;
    public static final SoundEvent entity_player_attack_weak;
    public static final SoundEvent entity_player_big_fall;
    public static final SoundEvent entity_player_breath;
    public static final SoundEvent entity_player_burp;
    public static final SoundEvent entity_player_death;
    public static final SoundEvent entity_player_hurt;
    public static final SoundEvent entity_player_levelup;
    public static final SoundEvent entity_player_small_fall;
    public static final SoundEvent entity_player_splash;
    public static final SoundEvent entity_player_swim;
    public static final SoundEvent block_portal_ambient;
    public static final SoundEvent block_portal_travel;
    public static final SoundEvent block_portal_trigger;
    public static final SoundEvent entity_rabbit_ambient;
    public static final SoundEvent entity_rabbit_attack;
    public static final SoundEvent entity_rabbit_death;
    public static final SoundEvent entity_rabbit_hurt;
    public static final SoundEvent entity_rabbit_jump;
    public static final SoundEvent record_11;
    public static final SoundEvent record_13;
    public static final SoundEvent record_blocks;
    public static final SoundEvent record_cat;
    public static final SoundEvent record_chirp;
    public static final SoundEvent record_far;
    public static final SoundEvent record_mall;
    public static final SoundEvent record_mellohi;
    public static final SoundEvent record_stal;
    public static final SoundEvent record_strad;
    public static final SoundEvent record_wait;
    public static final SoundEvent record_ward;
    public static final SoundEvent block_redstone_torch_burnout;
    public static final SoundEvent block_sand_break;
    public static final SoundEvent block_sand_fall;
    public static final SoundEvent block_sand_hit;
    public static final SoundEvent block_sand_place;
    public static final SoundEvent block_sand_step;
    public static final SoundEvent entity_sheep_ambient;
    public static final SoundEvent entity_sheep_death;
    public static final SoundEvent entity_sheep_hurt;
    public static final SoundEvent entity_sheep_shear;
    public static final SoundEvent entity_sheep_step;
    public static final SoundEvent item_shield_block;
    public static final SoundEvent item_shield_break;
    public static final SoundEvent item_shovel_flatten;
    public static final SoundEvent entity_shulker_ambient;
    public static final SoundEvent entity_shulker_bullet_hit;
    public static final SoundEvent entity_shulker_bullet_hurt;
    public static final SoundEvent entity_shulker_close;
    public static final SoundEvent entity_shulker_death;
    public static final SoundEvent entity_shulker_hurt;
    public static final SoundEvent entity_shulker_hurt_closed;
    public static final SoundEvent entity_shulker_open;
    public static final SoundEvent entity_shulker_shoot;
    public static final SoundEvent entity_shulker_teleport;
    public static final SoundEvent entity_silverfish_ambient;
    public static final SoundEvent entity_silverfish_death;
    public static final SoundEvent entity_silverfish_hurt;
    public static final SoundEvent entity_silverfish_step;
    public static final SoundEvent entity_skeleton_ambient;
    public static final SoundEvent entity_skeleton_death;
    public static final SoundEvent entity_skeleton_horse_ambient;
    public static final SoundEvent entity_skeleton_horse_death;
    public static final SoundEvent entity_skeleton_horse_hurt;
    public static final SoundEvent entity_skeleton_hurt;
    public static final SoundEvent entity_skeleton_shoot;
    public static final SoundEvent entity_skeleton_step;
    public static final SoundEvent entity_slime_attack;
    public static final SoundEvent block_slime_break;
    public static final SoundEvent entity_slime_death;
    public static final SoundEvent block_slime_fall;
    public static final SoundEvent block_slime_hit;
    public static final SoundEvent entity_slime_hurt;
    public static final SoundEvent entity_slime_jump;
    public static final SoundEvent block_slime_place;
    public static final SoundEvent entity_slime_squish;
    public static final SoundEvent block_slime_step;
    public static final SoundEvent entity_small_magmacube_death;
    public static final SoundEvent entity_small_magmacube_hurt;
    public static final SoundEvent entity_small_magmacube_squish;
    public static final SoundEvent entity_small_slime_death;
    public static final SoundEvent entity_small_slime_hurt;
    public static final SoundEvent entity_small_slime_jump;
    public static final SoundEvent entity_small_slime_squish;
    public static final SoundEvent entity_snowball_throw;
    public static final SoundEvent entity_snowman_ambient;
    public static final SoundEvent entity_snowman_death;
    public static final SoundEvent entity_snowman_hurt;
    public static final SoundEvent entity_snowman_shoot;
    public static final SoundEvent block_snow_break;
    public static final SoundEvent block_snow_fall;
    public static final SoundEvent block_snow_hit;
    public static final SoundEvent block_snow_place;
    public static final SoundEvent block_snow_step;
    public static final SoundEvent entity_spider_ambient;
    public static final SoundEvent entity_spider_death;
    public static final SoundEvent entity_spider_hurt;
    public static final SoundEvent entity_spider_step;
    public static final SoundEvent entity_splash_potion_break;
    public static final SoundEvent entity_splash_potion_throw;
    public static final SoundEvent entity_squid_ambient;
    public static final SoundEvent entity_squid_death;
    public static final SoundEvent entity_squid_hurt;
    public static final SoundEvent block_stone_break;
    public static final SoundEvent block_stone_button_click_off;
    public static final SoundEvent block_stone_button_click_on;
    public static final SoundEvent block_stone_fall;
    public static final SoundEvent block_stone_hit;
    public static final SoundEvent block_stone_place;
    public static final SoundEvent block_stone_pressplate_click_off;
    public static final SoundEvent block_stone_pressplate_click_on;
    public static final SoundEvent block_stone_step;
    public static final SoundEvent enchant_thorns_hit;
    public static final SoundEvent entity_tnt_primed;
    public static final SoundEvent block_tripwire_attach;
    public static final SoundEvent block_tripwire_click_off;
    public static final SoundEvent block_tripwire_click_on;
    public static final SoundEvent block_tripwire_detach;
    public static final SoundEvent ui_button_click;
    public static final SoundEvent entity_villager_ambient;
    public static final SoundEvent entity_villager_death;
    public static final SoundEvent entity_villager_hurt;
    public static final SoundEvent entity_villager_no;
    public static final SoundEvent entity_villager_trading;
    public static final SoundEvent entity_villager_yes;
    public static final SoundEvent block_waterlily_place;
    public static final SoundEvent block_water_ambient;
    public static final SoundEvent weather_rain;
    public static final SoundEvent weather_rain_above;
    public static final SoundEvent entity_witch_ambient;
    public static final SoundEvent entity_witch_death;
    public static final SoundEvent entity_witch_drink;
    public static final SoundEvent entity_witch_hurt;
    public static final SoundEvent entity_witch_throw;
    public static final SoundEvent entity_wither_ambient;
    public static final SoundEvent entity_wither_break_block;
    public static final SoundEvent entity_wither_death;
    public static final SoundEvent entity_wither_hurt;
    public static final SoundEvent entity_wither_shoot;
    public static final SoundEvent entity_wither_spawn;
    public static final SoundEvent entity_wolf_ambient;
    public static final SoundEvent entity_wolf_death;
    public static final SoundEvent entity_wolf_growl;
    public static final SoundEvent entity_wolf_howl;
    public static final SoundEvent entity_wolf_hurt;
    public static final SoundEvent entity_wolf_pant;
    public static final SoundEvent entity_wolf_shake;
    public static final SoundEvent entity_wolf_step;
    public static final SoundEvent entity_wolf_whine;
    public static final SoundEvent block_wooden_door_close;
    public static final SoundEvent block_wooden_door_open;
    public static final SoundEvent block_wooden_trapdoor_close;
    public static final SoundEvent block_wooden_trapdoor_open;
    public static final SoundEvent block_wood_break;
    public static final SoundEvent block_wood_button_click_off;
    public static final SoundEvent block_wood_button_click_on;
    public static final SoundEvent block_wood_fall;
    public static final SoundEvent block_wood_hit;
    public static final SoundEvent block_wood_place;
    public static final SoundEvent block_wood_pressplate_click_off;
    public static final SoundEvent block_wood_pressplate_click_on;
    public static final SoundEvent block_wood_step;
    public static final SoundEvent entity_zombie_ambient;
    public static final SoundEvent entity_zombie_attack_door_wood;
    public static final SoundEvent entity_zombie_attack_iron_door;
    public static final SoundEvent entity_zombie_break_door_wood;
    public static final SoundEvent entity_zombie_death;
    public static final SoundEvent entity_zombie_horse_ambient;
    public static final SoundEvent entity_zombie_horse_death;
    public static final SoundEvent entity_zombie_horse_hurt;
    public static final SoundEvent entity_zombie_hurt;
    public static final SoundEvent entity_zombie_infect;
    public static final SoundEvent entity_zombie_pig_ambient;
    public static final SoundEvent entity_zombie_pig_angry;
    public static final SoundEvent entity_zombie_pig_death;
    public static final SoundEvent entity_zombie_pig_hurt;
    public static final SoundEvent entity_zombie_step;
    public static final SoundEvent entity_zombie_villager_ambient;
    public static final SoundEvent entity_zombie_villager_converted;
    public static final SoundEvent entity_zombie_villager_cure;
    public static final SoundEvent entity_zombie_villager_death;
    public static final SoundEvent entity_zombie_villager_hurt;
    public static final SoundEvent entity_zombie_villager_step;

    private static SoundEvent getRegisteredSoundEvent(String id)
    {
        SoundEvent soundevent = (SoundEvent)SoundEvent.soundEventRegistry.getObject(new ResourceLocation(id));

        if (soundevent == null)
        {
            throw new IllegalStateException("Invalid Sound requested: " + id);
        }
        else
        {
            return soundevent;
        }
    }

    static
    {
        if (!Bootstrap.isRegistered())
        {
            throw new RuntimeException("Accessed Sounds before Bootstrap!");
        }
        else
        {
            ambient_cave = getRegisteredSoundEvent("ambient.cave");
            block_anvil_break = getRegisteredSoundEvent("block.anvil.break");
            block_anvil_destroy = getRegisteredSoundEvent("block.anvil.destroy");
            block_anvil_fall = getRegisteredSoundEvent("block.anvil.fall");
            block_anvil_hit = getRegisteredSoundEvent("block.anvil.hit");
            block_anvil_land = getRegisteredSoundEvent("block.anvil.land");
            block_anvil_place = getRegisteredSoundEvent("block.anvil.place");
            block_anvil_step = getRegisteredSoundEvent("block.anvil.step");
            block_anvil_use = getRegisteredSoundEvent("block.anvil.use");
            entity_armorstand_break = getRegisteredSoundEvent("entity.armorstand.break");
            entity_armorstand_fall = getRegisteredSoundEvent("entity.armorstand.fall");
            entity_armorstand_hit = getRegisteredSoundEvent("entity.armorstand.hit");
            entity_armorstand_place = getRegisteredSoundEvent("entity.armorstand.place");
            item_armor_equip_chain = getRegisteredSoundEvent("item.armor.equip_chain");
            item_armor_equip_diamond = getRegisteredSoundEvent("item.armor.equip_diamond");
            item_armor_equip_generic = getRegisteredSoundEvent("item.armor.equip_generic");
            item_armor_equip_gold = getRegisteredSoundEvent("item.armor.equip_gold");
            item_armor_equip_iron = getRegisteredSoundEvent("item.armor.equip_iron");
            item_armor_equip_leather = getRegisteredSoundEvent("item.armor.equip_leather");
            entity_arrow_hit = getRegisteredSoundEvent("entity.arrow.hit");
            entity_arrow_hit_player = getRegisteredSoundEvent("entity.arrow.hit_player");
            entity_arrow_shoot = getRegisteredSoundEvent("entity.arrow.shoot");
            entity_bat_ambient = getRegisteredSoundEvent("entity.bat.ambient");
            entity_bat_death = getRegisteredSoundEvent("entity.bat.death");
            entity_bat_hurt = getRegisteredSoundEvent("entity.bat.hurt");
            entity_bat_loop = getRegisteredSoundEvent("entity.bat.loop");
            entity_bat_takeoff = getRegisteredSoundEvent("entity.bat.takeoff");
            entity_blaze_ambient = getRegisteredSoundEvent("entity.blaze.ambient");
            entity_blaze_burn = getRegisteredSoundEvent("entity.blaze.burn");
            entity_blaze_death = getRegisteredSoundEvent("entity.blaze.death");
            entity_blaze_hurt = getRegisteredSoundEvent("entity.blaze.hurt");
            entity_blaze_shoot = getRegisteredSoundEvent("entity.blaze.shoot");
            entity_bobber_splash = getRegisteredSoundEvent("entity.bobber.splash");
            entity_bobber_throw = getRegisteredSoundEvent("entity.bobber.throw");
            item_bottle_fill = getRegisteredSoundEvent("item.bottle.fill");
            item_bottle_fill_dragonbreath = getRegisteredSoundEvent("item.bottle.fill_dragonbreath");
            block_brewing_stand_brew = getRegisteredSoundEvent("block.brewing_stand.brew");
            item_bucket_empty = getRegisteredSoundEvent("item.bucket.empty");
            item_bucket_empty_lava = getRegisteredSoundEvent("item.bucket.empty_lava");
            item_bucket_fill = getRegisteredSoundEvent("item.bucket.fill");
            item_bucket_fill_lava = getRegisteredSoundEvent("item.bucket.fill_lava");
            entity_cat_ambient = getRegisteredSoundEvent("entity.cat.ambient");
            entity_cat_death = getRegisteredSoundEvent("entity.cat.death");
            entity_cat_hiss = getRegisteredSoundEvent("entity.cat.hiss");
            entity_cat_hurt = getRegisteredSoundEvent("entity.cat.hurt");
            entity_cat_purr = getRegisteredSoundEvent("entity.cat.purr");
            entity_cat_purreow = getRegisteredSoundEvent("entity.cat.purreow");
            block_chest_close = getRegisteredSoundEvent("block.chest.close");
            block_chest_locked = getRegisteredSoundEvent("block.chest.locked");
            block_chest_open = getRegisteredSoundEvent("block.chest.open");
            entity_chicken_ambient = getRegisteredSoundEvent("entity.chicken.ambient");
            entity_chicken_death = getRegisteredSoundEvent("entity.chicken.death");
            entity_chicken_egg = getRegisteredSoundEvent("entity.chicken.egg");
            entity_chicken_hurt = getRegisteredSoundEvent("entity.chicken.hurt");
            entity_chicken_step = getRegisteredSoundEvent("entity.chicken.step");
            block_chorus_flower_death = getRegisteredSoundEvent("block.chorus_flower.death");
            block_chorus_flower_grow = getRegisteredSoundEvent("block.chorus_flower.grow");
            item_chorus_fruit_teleport = getRegisteredSoundEvent("item.chorus_fruit.teleport");
            block_cloth_break = getRegisteredSoundEvent("block.cloth.break");
            block_cloth_fall = getRegisteredSoundEvent("block.cloth.fall");
            block_cloth_hit = getRegisteredSoundEvent("block.cloth.hit");
            block_cloth_place = getRegisteredSoundEvent("block.cloth.place");
            block_cloth_step = getRegisteredSoundEvent("block.cloth.step");
            block_comparator_click = getRegisteredSoundEvent("block.comparator.click");
            entity_cow_ambient = getRegisteredSoundEvent("entity.cow.ambient");
            entity_cow_death = getRegisteredSoundEvent("entity.cow.death");
            entity_cow_hurt = getRegisteredSoundEvent("entity.cow.hurt");
            entity_cow_milk = getRegisteredSoundEvent("entity.cow.milk");
            entity_cow_step = getRegisteredSoundEvent("entity.cow.step");
            entity_creeper_death = getRegisteredSoundEvent("entity.creeper.death");
            entity_creeper_hurt = getRegisteredSoundEvent("entity.creeper.hurt");
            entity_creeper_primed = getRegisteredSoundEvent("entity.creeper.primed");
            block_dispenser_dispense = getRegisteredSoundEvent("block.dispenser.dispense");
            block_dispenser_fail = getRegisteredSoundEvent("block.dispenser.fail");
            block_dispenser_launch = getRegisteredSoundEvent("block.dispenser.launch");
            entity_donkey_ambient = getRegisteredSoundEvent("entity.donkey.ambient");
            entity_donkey_angry = getRegisteredSoundEvent("entity.donkey.angry");
            entity_donkey_chest = getRegisteredSoundEvent("entity.donkey.chest");
            entity_donkey_death = getRegisteredSoundEvent("entity.donkey.death");
            entity_donkey_hurt = getRegisteredSoundEvent("entity.donkey.hurt");
            entity_egg_throw = getRegisteredSoundEvent("entity.egg.throw");
            entity_elder_guardian_ambient = getRegisteredSoundEvent("entity.elder_guardian.ambient");
            entity_elderguardian_ambientland = getRegisteredSoundEvent("entity.elder_guardian.ambient_land");
            entity_elder_guardian_curse = getRegisteredSoundEvent("entity.elder_guardian.curse");
            entity_elder_guardian_death = getRegisteredSoundEvent("entity.elder_guardian.death");
            entity_elder_guardian_death_land = getRegisteredSoundEvent("entity.elder_guardian.death_land");
            entity_elder_guardian_hurt = getRegisteredSoundEvent("entity.elder_guardian.hurt");
            entity_elder_guardian_hurt_land = getRegisteredSoundEvent("entity.elder_guardian.hurt_land");
            block_enderchest_close = getRegisteredSoundEvent("block.enderchest.close");
            block_enderchest_open = getRegisteredSoundEvent("block.enderchest.open");
            entity_enderdragon_ambient = getRegisteredSoundEvent("entity.enderdragon.ambient");
            entity_enderdragon_death = getRegisteredSoundEvent("entity.enderdragon.death");
            entity_enderdragon_fireball_epld = getRegisteredSoundEvent("entity.enderdragon_fireball.explode");
            entity_enderdragon_flap = getRegisteredSoundEvent("entity.enderdragon.flap");
            entity_enderdragon_growl = getRegisteredSoundEvent("entity.enderdragon.growl");
            entity_enderdragon_hurt = getRegisteredSoundEvent("entity.enderdragon.hurt");
            entity_enderdragon_shoot = getRegisteredSoundEvent("entity.enderdragon.shoot");
            entity_endereye_launch = getRegisteredSoundEvent("entity.endereye.launch");
            entity_endermen_ambient = getRegisteredSoundEvent("entity.endermen.ambient");
            entity_endermen_death = getRegisteredSoundEvent("entity.endermen.death");
            entity_endermen_hurt = getRegisteredSoundEvent("entity.endermen.hurt");
            entity_endermen_scream = getRegisteredSoundEvent("entity.endermen.scream");
            entity_endermen_stare = getRegisteredSoundEvent("entity.endermen.stare");
            entity_endermen_teleport = getRegisteredSoundEvent("entity.endermen.teleport");
            entity_endermite_ambient = getRegisteredSoundEvent("entity.endermite.ambient");
            entity_endermite_death = getRegisteredSoundEvent("entity.endermite.death");
            entity_endermite_hurt = getRegisteredSoundEvent("entity.endermite.hurt");
            entity_endermite_step = getRegisteredSoundEvent("entity.endermite.step");
            entity_enderpearl_throw = getRegisteredSoundEvent("entity.enderpearl.throw");
            block_end_gateway_spawn = getRegisteredSoundEvent("block.end_gateway.spawn");
            entity_experience_bottle_throw = getRegisteredSoundEvent("entity.experience_bottle.throw");
            entity_experience_orb_pickup = getRegisteredSoundEvent("entity.experience_orb.pickup");
            entity_experience_orb_touch = getRegisteredSoundEvent("entity.experience_orb.touch");
            block_fence_gate_close = getRegisteredSoundEvent("block.fence_gate.close");
            block_fence_gate_open = getRegisteredSoundEvent("block.fence_gate.open");
            item_firecharge_use = getRegisteredSoundEvent("item.firecharge.use");
            entity_firework_blast = getRegisteredSoundEvent("entity.firework.blast");
            entity_firework_blast_far = getRegisteredSoundEvent("entity.firework.blast_far");
            entity_firework_large_blast = getRegisteredSoundEvent("entity.firework.large_blast");
            entity_firework_large_blast_far = getRegisteredSoundEvent("entity.firework.large_blast_far");
            entity_firework_launch = getRegisteredSoundEvent("entity.firework.launch");
            entity_firework_shoot = getRegisteredSoundEvent("entity.firework.shoot");
            entity_firework_twinkle = getRegisteredSoundEvent("entity.firework.twinkle");
            entity_firework_twinkle_far = getRegisteredSoundEvent("entity.firework.twinkle_far");
            block_fire_ambient = getRegisteredSoundEvent("block.fire.ambient");
            block_fire_extinguish = getRegisteredSoundEvent("block.fire.extinguish");
            item_flintandsteel_use = getRegisteredSoundEvent("item.flintandsteel.use");
            block_furnace_fire_crackle = getRegisteredSoundEvent("block.furnace.fire_crackle");
            entity_generic_big_fall = getRegisteredSoundEvent("entity.generic.big_fall");
            entity_generic_burn = getRegisteredSoundEvent("entity.generic.burn");
            entity_generic_death = getRegisteredSoundEvent("entity.generic.death");
            entity_generic_drink = getRegisteredSoundEvent("entity.generic.drink");
            entity_generic_eat = getRegisteredSoundEvent("entity.generic.eat");
            entity_generic_explode = getRegisteredSoundEvent("entity.generic.explode");
            entity_generic_extinguish_fire = getRegisteredSoundEvent("entity.generic.extinguish_fire");
            entity_generic_hurt = getRegisteredSoundEvent("entity.generic.hurt");
            entity_generic_small_fall = getRegisteredSoundEvent("entity.generic.small_fall");
            entity_generic_splash = getRegisteredSoundEvent("entity.generic.splash");
            entity_generic_swim = getRegisteredSoundEvent("entity.generic.swim");
            entity_ghast_ambient = getRegisteredSoundEvent("entity.ghast.ambient");
            entity_ghast_death = getRegisteredSoundEvent("entity.ghast.death");
            entity_ghast_hurt = getRegisteredSoundEvent("entity.ghast.hurt");
            entity_ghast_scream = getRegisteredSoundEvent("entity.ghast.scream");
            entity_ghast_shoot = getRegisteredSoundEvent("entity.ghast.shoot");
            entity_ghast_warn = getRegisteredSoundEvent("entity.ghast.warn");
            block_glass_break = getRegisteredSoundEvent("block.glass.break");
            block_glass_fall = getRegisteredSoundEvent("block.glass.fall");
            block_glass_hit = getRegisteredSoundEvent("block.glass.hit");
            block_glass_place = getRegisteredSoundEvent("block.glass.place");
            block_glass_step = getRegisteredSoundEvent("block.glass.step");
            block_grass_break = getRegisteredSoundEvent("block.grass.break");
            block_grass_fall = getRegisteredSoundEvent("block.grass.fall");
            block_grass_hit = getRegisteredSoundEvent("block.grass.hit");
            block_grass_place = getRegisteredSoundEvent("block.grass.place");
            block_grass_step = getRegisteredSoundEvent("block.grass.step");
            block_gravel_break = getRegisteredSoundEvent("block.gravel.break");
            block_gravel_fall = getRegisteredSoundEvent("block.gravel.fall");
            block_gravel_hit = getRegisteredSoundEvent("block.gravel.hit");
            block_gravel_place = getRegisteredSoundEvent("block.gravel.place");
            block_gravel_step = getRegisteredSoundEvent("block.gravel.step");
            entity_guardian_ambient = getRegisteredSoundEvent("entity.guardian.ambient");
            entity_guardian_ambient_land = getRegisteredSoundEvent("entity.guardian.ambient_land");
            entity_guardian_attack = getRegisteredSoundEvent("entity.guardian.attack");
            entity_guardian_death = getRegisteredSoundEvent("entity.guardian.death");
            entity_guardian_death_land = getRegisteredSoundEvent("entity.guardian.death_land");
            entity_guardian_flop = getRegisteredSoundEvent("entity.guardian.flop");
            entity_guardian_hurt = getRegisteredSoundEvent("entity.guardian.hurt");
            entity_guardian_hurt_land = getRegisteredSoundEvent("entity.guardian.hurt_land");
            item_hoe_till = getRegisteredSoundEvent("item.hoe.till");
            entity_horse_ambient = getRegisteredSoundEvent("entity.horse.ambient");
            entity_horse_angry = getRegisteredSoundEvent("entity.horse.angry");
            entity_horse_armor = getRegisteredSoundEvent("entity.horse.armor");
            entity_horse_breathe = getRegisteredSoundEvent("entity.horse.breathe");
            entity_horse_death = getRegisteredSoundEvent("entity.horse.death");
            entity_horse_eat = getRegisteredSoundEvent("entity.horse.eat");
            entity_horse_gallop = getRegisteredSoundEvent("entity.horse.gallop");
            entity_horse_hurt = getRegisteredSoundEvent("entity.horse.hurt");
            entity_horse_jump = getRegisteredSoundEvent("entity.horse.jump");
            entity_horse_land = getRegisteredSoundEvent("entity.horse.land");
            entity_horse_saddle = getRegisteredSoundEvent("entity.horse.saddle");
            entity_horse_step = getRegisteredSoundEvent("entity.horse.step");
            entity_horse_step_wood = getRegisteredSoundEvent("entity.horse.step_wood");
            entity_hostile_big_fall = getRegisteredSoundEvent("entity.hostile.big_fall");
            entity_hostile_death = getRegisteredSoundEvent("entity.hostile.death");
            entity_hostile_hurt = getRegisteredSoundEvent("entity.hostile.hurt");
            entity_hostile_small_fall = getRegisteredSoundEvent("entity.hostile.small_fall");
            entity_hostile_splash = getRegisteredSoundEvent("entity.hostile.splash");
            entity_hostile_swim = getRegisteredSoundEvent("entity.hostile.swim");
            entity_irongolem_attack = getRegisteredSoundEvent("entity.irongolem.attack");
            entity_irongolem_death = getRegisteredSoundEvent("entity.irongolem.death");
            entity_irongolem_hurt = getRegisteredSoundEvent("entity.irongolem.hurt");
            entity_irongolem_step = getRegisteredSoundEvent("entity.irongolem.step");
            block_iron_door_close = getRegisteredSoundEvent("block.iron_door.close");
            block_iron_door_open = getRegisteredSoundEvent("block.iron_door.open");
            block_iron_trapdoor_close = getRegisteredSoundEvent("block.iron_trapdoor.close");
            block_iron_trapdoor_open = getRegisteredSoundEvent("block.iron_trapdoor.open");
            entity_itemframe_add_item = getRegisteredSoundEvent("entity.itemframe.add_item");
            entity_itemframe_break = getRegisteredSoundEvent("entity.itemframe.break");
            entity_itemframe_place = getRegisteredSoundEvent("entity.itemframe.place");
            entity_itemframe_remove_item = getRegisteredSoundEvent("entity.itemframe.remove_item");
            entity_itemframe_rotate_item = getRegisteredSoundEvent("entity.itemframe.rotate_item");
            entity_item_break = getRegisteredSoundEvent("entity.item.break");
            entity_item_pickup = getRegisteredSoundEvent("entity.item.pickup");
            block_ladder_break = getRegisteredSoundEvent("block.ladder.break");
            block_ladder_fall = getRegisteredSoundEvent("block.ladder.fall");
            block_ladder_hit = getRegisteredSoundEvent("block.ladder.hit");
            block_ladder_place = getRegisteredSoundEvent("block.ladder.place");
            block_ladder_step = getRegisteredSoundEvent("block.ladder.step");
            block_lava_ambient = getRegisteredSoundEvent("block.lava.ambient");
            block_lava_extinguish = getRegisteredSoundEvent("block.lava.extinguish");
            block_lava_pop = getRegisteredSoundEvent("block.lava.pop");
            entity_leashknot_break = getRegisteredSoundEvent("entity.leashknot.break");
            entity_leashknot_place = getRegisteredSoundEvent("entity.leashknot.place");
            block_lever_click = getRegisteredSoundEvent("block.lever.click");
            entity_lightning_impact = getRegisteredSoundEvent("entity.lightning.impact");
            entity_lightning_thunder = getRegisteredSoundEvent("entity.lightning.thunder");
            entity_lingeringpotion_throw = getRegisteredSoundEvent("entity.lingeringpotion.throw");
            entity_magmacube_death = getRegisteredSoundEvent("entity.magmacube.death");
            entity_magmacube_hurt = getRegisteredSoundEvent("entity.magmacube.hurt");
            entity_magmacube_jump = getRegisteredSoundEvent("entity.magmacube.jump");
            entity_magmacube_squish = getRegisteredSoundEvent("entity.magmacube.squish");
            block_metal_break = getRegisteredSoundEvent("block.metal.break");
            block_metal_fall = getRegisteredSoundEvent("block.metal.fall");
            block_metal_hit = getRegisteredSoundEvent("block.metal.hit");
            block_metal_place = getRegisteredSoundEvent("block.metal.place");
            block_metal_pressplate_click_off = getRegisteredSoundEvent("block.metal_pressureplate.click_off");
            block_metal_pressplate_click_on = getRegisteredSoundEvent("block.metal_pressureplate.click_on");
            block_metal_step = getRegisteredSoundEvent("block.metal.step");
            entity_minecart_inside = getRegisteredSoundEvent("entity.minecart.inside");
            entity_minecart_riding = getRegisteredSoundEvent("entity.minecart.riding");
            entity_mooshroom_shear = getRegisteredSoundEvent("entity.mooshroom.shear");
            entity_mule_ambient = getRegisteredSoundEvent("entity.mule.ambient");
            entity_mule_death = getRegisteredSoundEvent("entity.mule.death");
            entity_mule_hurt = getRegisteredSoundEvent("entity.mule.hurt");
            music_creative = getRegisteredSoundEvent("music.creative");
            music_credits = getRegisteredSoundEvent("music.credits");
            music_dragon = getRegisteredSoundEvent("music.dragon");
            music_end = getRegisteredSoundEvent("music.end");
            music_game = getRegisteredSoundEvent("music.game");
            music_menu = getRegisteredSoundEvent("music.menu");
            music_nether = getRegisteredSoundEvent("music.nether");
            block_note_basedrum = getRegisteredSoundEvent("block.note.basedrum");
            block_note_bass = getRegisteredSoundEvent("block.note.bass");
            block_note_harp = getRegisteredSoundEvent("block.note.harp");
            block_note_hat = getRegisteredSoundEvent("block.note.hat");
            block_note_pling = getRegisteredSoundEvent("block.note.pling");
            block_note_snare = getRegisteredSoundEvent("block.note.snare");
            entity_painting_break = getRegisteredSoundEvent("entity.painting.break");
            entity_painting_place = getRegisteredSoundEvent("entity.painting.place");
            entity_pig_ambient = getRegisteredSoundEvent("entity.pig.ambient");
            entity_pig_death = getRegisteredSoundEvent("entity.pig.death");
            entity_pig_hurt = getRegisteredSoundEvent("entity.pig.hurt");
            entity_pig_saddle = getRegisteredSoundEvent("entity.pig.saddle");
            entity_pig_step = getRegisteredSoundEvent("entity.pig.step");
            block_piston_contract = getRegisteredSoundEvent("block.piston.contract");
            block_piston_extend = getRegisteredSoundEvent("block.piston.extend");
            entity_player_attack_crit = getRegisteredSoundEvent("entity.player.attack.crit");
            entity_player_attack_knockback = getRegisteredSoundEvent("entity.player.attack.knockback");
            entity_player_attack_nodamage = getRegisteredSoundEvent("entity.player.attack.nodamage");
            entity_player_attack_strong = getRegisteredSoundEvent("entity.player.attack.strong");
            entity_player_attack_sweep = getRegisteredSoundEvent("entity.player.attack.sweep");
            entity_player_attack_weak = getRegisteredSoundEvent("entity.player.attack.weak");
            entity_player_big_fall = getRegisteredSoundEvent("entity.player.big_fall");
            entity_player_breath = getRegisteredSoundEvent("entity.player.breath");
            entity_player_burp = getRegisteredSoundEvent("entity.player.burp");
            entity_player_death = getRegisteredSoundEvent("entity.player.death");
            entity_player_hurt = getRegisteredSoundEvent("entity.player.hurt");
            entity_player_levelup = getRegisteredSoundEvent("entity.player.levelup");
            entity_player_small_fall = getRegisteredSoundEvent("entity.player.small_fall");
            entity_player_splash = getRegisteredSoundEvent("entity.player.splash");
            entity_player_swim = getRegisteredSoundEvent("entity.player.swim");
            block_portal_ambient = getRegisteredSoundEvent("block.portal.ambient");
            block_portal_travel = getRegisteredSoundEvent("block.portal.travel");
            block_portal_trigger = getRegisteredSoundEvent("block.portal.trigger");
            entity_rabbit_ambient = getRegisteredSoundEvent("entity.rabbit.ambient");
            entity_rabbit_attack = getRegisteredSoundEvent("entity.rabbit.attack");
            entity_rabbit_death = getRegisteredSoundEvent("entity.rabbit.death");
            entity_rabbit_hurt = getRegisteredSoundEvent("entity.rabbit.hurt");
            entity_rabbit_jump = getRegisteredSoundEvent("entity.rabbit.jump");
            record_11 = getRegisteredSoundEvent("record.11");
            record_13 = getRegisteredSoundEvent("record.13");
            record_blocks = getRegisteredSoundEvent("record.blocks");
            record_cat = getRegisteredSoundEvent("record.cat");
            record_chirp = getRegisteredSoundEvent("record.chirp");
            record_far = getRegisteredSoundEvent("record.far");
            record_mall = getRegisteredSoundEvent("record.mall");
            record_mellohi = getRegisteredSoundEvent("record.mellohi");
            record_stal = getRegisteredSoundEvent("record.stal");
            record_strad = getRegisteredSoundEvent("record.strad");
            record_wait = getRegisteredSoundEvent("record.wait");
            record_ward = getRegisteredSoundEvent("record.ward");
            block_redstone_torch_burnout = getRegisteredSoundEvent("block.redstone_torch.burnout");
            block_sand_break = getRegisteredSoundEvent("block.sand.break");
            block_sand_fall = getRegisteredSoundEvent("block.sand.fall");
            block_sand_hit = getRegisteredSoundEvent("block.sand.hit");
            block_sand_place = getRegisteredSoundEvent("block.sand.place");
            block_sand_step = getRegisteredSoundEvent("block.sand.step");
            entity_sheep_ambient = getRegisteredSoundEvent("entity.sheep.ambient");
            entity_sheep_death = getRegisteredSoundEvent("entity.sheep.death");
            entity_sheep_hurt = getRegisteredSoundEvent("entity.sheep.hurt");
            entity_sheep_shear = getRegisteredSoundEvent("entity.sheep.shear");
            entity_sheep_step = getRegisteredSoundEvent("entity.sheep.step");
            item_shield_block = getRegisteredSoundEvent("item.shield.block");
            item_shield_break = getRegisteredSoundEvent("item.shield.break");
            item_shovel_flatten = getRegisteredSoundEvent("item.shovel.flatten");
            entity_shulker_ambient = getRegisteredSoundEvent("entity.shulker.ambient");
            entity_shulker_bullet_hit = getRegisteredSoundEvent("entity.shulker_bullet.hit");
            entity_shulker_bullet_hurt = getRegisteredSoundEvent("entity.shulker_bullet.hurt");
            entity_shulker_close = getRegisteredSoundEvent("entity.shulker.close");
            entity_shulker_death = getRegisteredSoundEvent("entity.shulker.death");
            entity_shulker_hurt = getRegisteredSoundEvent("entity.shulker.hurt");
            entity_shulker_hurt_closed = getRegisteredSoundEvent("entity.shulker.hurt_closed");
            entity_shulker_open = getRegisteredSoundEvent("entity.shulker.open");
            entity_shulker_shoot = getRegisteredSoundEvent("entity.shulker.shoot");
            entity_shulker_teleport = getRegisteredSoundEvent("entity.shulker.teleport");
            entity_silverfish_ambient = getRegisteredSoundEvent("entity.silverfish.ambient");
            entity_silverfish_death = getRegisteredSoundEvent("entity.silverfish.death");
            entity_silverfish_hurt = getRegisteredSoundEvent("entity.silverfish.hurt");
            entity_silverfish_step = getRegisteredSoundEvent("entity.silverfish.step");
            entity_skeleton_ambient = getRegisteredSoundEvent("entity.skeleton.ambient");
            entity_skeleton_death = getRegisteredSoundEvent("entity.skeleton.death");
            entity_skeleton_horse_ambient = getRegisteredSoundEvent("entity.skeleton_horse.ambient");
            entity_skeleton_horse_death = getRegisteredSoundEvent("entity.skeleton_horse.death");
            entity_skeleton_horse_hurt = getRegisteredSoundEvent("entity.skeleton_horse.hurt");
            entity_skeleton_hurt = getRegisteredSoundEvent("entity.skeleton.hurt");
            entity_skeleton_shoot = getRegisteredSoundEvent("entity.skeleton.shoot");
            entity_skeleton_step = getRegisteredSoundEvent("entity.skeleton.step");
            entity_slime_attack = getRegisteredSoundEvent("entity.slime.attack");
            block_slime_break = getRegisteredSoundEvent("block.slime.break");
            entity_slime_death = getRegisteredSoundEvent("entity.slime.death");
            block_slime_fall = getRegisteredSoundEvent("block.slime.fall");
            block_slime_hit = getRegisteredSoundEvent("block.slime.hit");
            entity_slime_hurt = getRegisteredSoundEvent("entity.slime.hurt");
            entity_slime_jump = getRegisteredSoundEvent("entity.slime.jump");
            block_slime_place = getRegisteredSoundEvent("block.slime.place");
            entity_slime_squish = getRegisteredSoundEvent("entity.slime.squish");
            block_slime_step = getRegisteredSoundEvent("block.slime.step");
            entity_small_magmacube_death = getRegisteredSoundEvent("entity.small_magmacube.death");
            entity_small_magmacube_hurt = getRegisteredSoundEvent("entity.small_magmacube.hurt");
            entity_small_magmacube_squish = getRegisteredSoundEvent("entity.small_magmacube.squish");
            entity_small_slime_death = getRegisteredSoundEvent("entity.small_slime.death");
            entity_small_slime_hurt = getRegisteredSoundEvent("entity.small_slime.hurt");
            entity_small_slime_jump = getRegisteredSoundEvent("entity.small_slime.jump");
            entity_small_slime_squish = getRegisteredSoundEvent("entity.small_slime.squish");
            entity_snowball_throw = getRegisteredSoundEvent("entity.snowball.throw");
            entity_snowman_ambient = getRegisteredSoundEvent("entity.snowman.ambient");
            entity_snowman_death = getRegisteredSoundEvent("entity.snowman.death");
            entity_snowman_hurt = getRegisteredSoundEvent("entity.snowman.hurt");
            entity_snowman_shoot = getRegisteredSoundEvent("entity.snowman.shoot");
            block_snow_break = getRegisteredSoundEvent("block.snow.break");
            block_snow_fall = getRegisteredSoundEvent("block.snow.fall");
            block_snow_hit = getRegisteredSoundEvent("block.snow.hit");
            block_snow_place = getRegisteredSoundEvent("block.snow.place");
            block_snow_step = getRegisteredSoundEvent("block.snow.step");
            entity_spider_ambient = getRegisteredSoundEvent("entity.spider.ambient");
            entity_spider_death = getRegisteredSoundEvent("entity.spider.death");
            entity_spider_hurt = getRegisteredSoundEvent("entity.spider.hurt");
            entity_spider_step = getRegisteredSoundEvent("entity.spider.step");
            entity_splash_potion_break = getRegisteredSoundEvent("entity.splash_potion.break");
            entity_splash_potion_throw = getRegisteredSoundEvent("entity.splash_potion.throw");
            entity_squid_ambient = getRegisteredSoundEvent("entity.squid.ambient");
            entity_squid_death = getRegisteredSoundEvent("entity.squid.death");
            entity_squid_hurt = getRegisteredSoundEvent("entity.squid.hurt");
            block_stone_break = getRegisteredSoundEvent("block.stone.break");
            block_stone_button_click_off = getRegisteredSoundEvent("block.stone_button.click_off");
            block_stone_button_click_on = getRegisteredSoundEvent("block.stone_button.click_on");
            block_stone_fall = getRegisteredSoundEvent("block.stone.fall");
            block_stone_hit = getRegisteredSoundEvent("block.stone.hit");
            block_stone_place = getRegisteredSoundEvent("block.stone.place");
            block_stone_pressplate_click_off = getRegisteredSoundEvent("block.stone_pressureplate.click_off");
            block_stone_pressplate_click_on = getRegisteredSoundEvent("block.stone_pressureplate.click_on");
            block_stone_step = getRegisteredSoundEvent("block.stone.step");
            enchant_thorns_hit = getRegisteredSoundEvent("enchant.thorns.hit");
            entity_tnt_primed = getRegisteredSoundEvent("entity.tnt.primed");
            block_tripwire_attach = getRegisteredSoundEvent("block.tripwire.attach");
            block_tripwire_click_off = getRegisteredSoundEvent("block.tripwire.click_off");
            block_tripwire_click_on = getRegisteredSoundEvent("block.tripwire.click_on");
            block_tripwire_detach = getRegisteredSoundEvent("block.tripwire.detach");
            ui_button_click = getRegisteredSoundEvent("ui.button.click");
            entity_villager_ambient = getRegisteredSoundEvent("entity.villager.ambient");
            entity_villager_death = getRegisteredSoundEvent("entity.villager.death");
            entity_villager_hurt = getRegisteredSoundEvent("entity.villager.hurt");
            entity_villager_no = getRegisteredSoundEvent("entity.villager.no");
            entity_villager_trading = getRegisteredSoundEvent("entity.villager.trading");
            entity_villager_yes = getRegisteredSoundEvent("entity.villager.yes");
            block_waterlily_place = getRegisteredSoundEvent("block.waterlily.place");
            block_water_ambient = getRegisteredSoundEvent("block.water.ambient");
            weather_rain = getRegisteredSoundEvent("weather.rain");
            weather_rain_above = getRegisteredSoundEvent("weather.rain.above");
            entity_witch_ambient = getRegisteredSoundEvent("entity.witch.ambient");
            entity_witch_death = getRegisteredSoundEvent("entity.witch.death");
            entity_witch_drink = getRegisteredSoundEvent("entity.witch.drink");
            entity_witch_hurt = getRegisteredSoundEvent("entity.witch.hurt");
            entity_witch_throw = getRegisteredSoundEvent("entity.witch.throw");
            entity_wither_ambient = getRegisteredSoundEvent("entity.wither.ambient");
            entity_wither_break_block = getRegisteredSoundEvent("entity.wither.break_block");
            entity_wither_death = getRegisteredSoundEvent("entity.wither.death");
            entity_wither_hurt = getRegisteredSoundEvent("entity.wither.hurt");
            entity_wither_shoot = getRegisteredSoundEvent("entity.wither.shoot");
            entity_wither_spawn = getRegisteredSoundEvent("entity.wither.spawn");
            entity_wolf_ambient = getRegisteredSoundEvent("entity.wolf.ambient");
            entity_wolf_death = getRegisteredSoundEvent("entity.wolf.death");
            entity_wolf_growl = getRegisteredSoundEvent("entity.wolf.growl");
            entity_wolf_howl = getRegisteredSoundEvent("entity.wolf.howl");
            entity_wolf_hurt = getRegisteredSoundEvent("entity.wolf.hurt");
            entity_wolf_pant = getRegisteredSoundEvent("entity.wolf.pant");
            entity_wolf_shake = getRegisteredSoundEvent("entity.wolf.shake");
            entity_wolf_step = getRegisteredSoundEvent("entity.wolf.step");
            entity_wolf_whine = getRegisteredSoundEvent("entity.wolf.whine");
            block_wooden_door_close = getRegisteredSoundEvent("block.wooden_door.close");
            block_wooden_door_open = getRegisteredSoundEvent("block.wooden_door.open");
            block_wooden_trapdoor_close = getRegisteredSoundEvent("block.wooden_trapdoor.close");
            block_wooden_trapdoor_open = getRegisteredSoundEvent("block.wooden_trapdoor.open");
            block_wood_break = getRegisteredSoundEvent("block.wood.break");
            block_wood_button_click_off = getRegisteredSoundEvent("block.wood_button.click_off");
            block_wood_button_click_on = getRegisteredSoundEvent("block.wood_button.click_on");
            block_wood_fall = getRegisteredSoundEvent("block.wood.fall");
            block_wood_hit = getRegisteredSoundEvent("block.wood.hit");
            block_wood_place = getRegisteredSoundEvent("block.wood.place");
            block_wood_pressplate_click_off = getRegisteredSoundEvent("block.wood_pressureplate.click_off");
            block_wood_pressplate_click_on = getRegisteredSoundEvent("block.wood_pressureplate.click_on");
            block_wood_step = getRegisteredSoundEvent("block.wood.step");
            entity_zombie_ambient = getRegisteredSoundEvent("entity.zombie.ambient");
            entity_zombie_attack_door_wood = getRegisteredSoundEvent("entity.zombie.attack_door_wood");
            entity_zombie_attack_iron_door = getRegisteredSoundEvent("entity.zombie.attack_iron_door");
            entity_zombie_break_door_wood = getRegisteredSoundEvent("entity.zombie.break_door_wood");
            entity_zombie_death = getRegisteredSoundEvent("entity.zombie.death");
            entity_zombie_horse_ambient = getRegisteredSoundEvent("entity.zombie_horse.ambient");
            entity_zombie_horse_death = getRegisteredSoundEvent("entity.zombie_horse.death");
            entity_zombie_horse_hurt = getRegisteredSoundEvent("entity.zombie_horse.hurt");
            entity_zombie_hurt = getRegisteredSoundEvent("entity.zombie.hurt");
            entity_zombie_infect = getRegisteredSoundEvent("entity.zombie.infect");
            entity_zombie_pig_ambient = getRegisteredSoundEvent("entity.zombie_pig.ambient");
            entity_zombie_pig_angry = getRegisteredSoundEvent("entity.zombie_pig.angry");
            entity_zombie_pig_death = getRegisteredSoundEvent("entity.zombie_pig.death");
            entity_zombie_pig_hurt = getRegisteredSoundEvent("entity.zombie_pig.hurt");
            entity_zombie_step = getRegisteredSoundEvent("entity.zombie.step");
            entity_zombie_villager_ambient = getRegisteredSoundEvent("entity.zombie_villager.ambient");
            entity_zombie_villager_converted = getRegisteredSoundEvent("entity.zombie_villager.converted");
            entity_zombie_villager_cure = getRegisteredSoundEvent("entity.zombie_villager.cure");
            entity_zombie_villager_death = getRegisteredSoundEvent("entity.zombie_villager.death");
            entity_zombie_villager_hurt = getRegisteredSoundEvent("entity.zombie_villager.hurt");
            entity_zombie_villager_step = getRegisteredSoundEvent("entity.zombie_villager.step");
        }
    }
}
